site_name: ThrottleKit
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top

nav:
  - 'Getting Started': index.md
  - 'Middleware':
    - 'FastAPI': middleware/fastapi.md
    - 'Flask': middleware/flask.md
  - 'Algorithms': algorithms.md
  - 'Backends': backends.md
  - 'API Reference': api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: no
